Product.create!([
  {name: "Beledros Witherbloom", price: "13.0", image_url: "https://product-images.tcgplayer.com/fit-in/641x641/235969.jpg", description: "Beledros Witherbloom is one of the five elder dragons from Arcavios that founded Strixhaven. The {B}{G} Witherbloom College is named in her honor.", inventory: 7},
  {name: "Shadrix Silverquill", price: "3.0", image_url: "https://cdn.ionsuite.com/image/ion-prime/data/mtg/stx/235173_200w-800x800.jpg", description: "Shadrix Silverquill is one of the five elder dragons from Arcavios that founded Strixhaven. The {W}{B} Silverquill College is named in his honor.", inventory: 3},
  {name: "Dragonlord Dramoka", price: "28.0", image_url: "https://product-images.tcgplayer.com/fit-in/641x641/96467.jpg", description: "Dromoka is one of the five elder dragons of Tarkir. She is a robust, ankylosaur-like beast, well protected by scaly armor, and is able to breathe searing beams of light. She is a patient, merciful leader, but in battle, she does not hesitate to unleash her breath weapon to obliterate those who dare stand against her.", inventory: 3},
  {name: "Dragonlord Ojutai", price: "3.0", image_url: "https://product-images.tcgplayer.com/fit-in/641x641/96503.jpg", description: "Ojutai, a.k.a. the Soul of Winter or the Great Teacher is one of the five elder dragons of Tarkir. He is a lithe, feathered winged creature with an icy breath. He is considered to be insightful and wise, though several of his actions in-story are motivated by spite.", inventory: 19},
  {name: "Dragonlord Atarka", price: "5.0", image_url: "https://product-images.tcgplayer.com/fit-in/641x641/96507.jpg", description: "Atarka is one of the five elder dragons of Tarkir. She is a robust beast with antlers, horns, and fur. She breathes green flames. The ultimate predator, Atarka spends her days, and most of her nights, hunting and feasting.", inventory: 8},
  {name: "Tanazir Quandrix", price: "2.0", image_url: "https://product-images.tcgplayer.com/fit-in/368x368/235664.jpg", description: "Tanazir Quandrix is one of the five elder dragons from Arcavios that founded Strixhaven. The {G}{U} Quandrix College is named in her honor.", inventory: 22},
  {name: "Velomachus Lorehold", price: "6.0", image_url: "https://product-images.tcgplayer.com/fit-in/400x558/235635.jpg", description: "Velomachus Lorehold is one of the five elder dragons from Arcavios that founded Strixhaven. The {R}{W} Lorehold College is named in her honor. It is said she was once cured of a secret illness by Dean Lisette of Witherbloom College.", inventory: 5},
  {name: "Galazeth Prismari", price: "5.0", image_url: "https://product-images.tcgplayer.com/fit-in/400x558/235853.jpg", description: "Galazeth Prismari is one of the five elder dragons from Arcavios that founded Strixhaven. He has a flair for the dramatic and the {U}{R} Prismari College is named in his honor.", inventory: 6},
  {name: "Dragonlord Kolaghan", price: "8.0", image_url: "https://product-images.tcgplayer.com/fit-in/641x641/96486.jpg", description: "Kolaghan is one of the five elder dragons of Tarkir. She is titanic, covered in spines, features four feathered wings, and is able to breathe lightning. Feral and brutal, she enjoys the hunt and the kill more than the resulting meal. Unlike the other dragons, Kolaghan does not appear to speak draconic, only communicating in lightning flashes and violence.", inventory: 6},
  {name: "Dragonlord Silumgar", price: "11.0", image_url: "https://product-images.tcgplayer.com/fit-in/641x641/96136.jpg", description: "Silumgar is one of the five elder dragons of Tarkir. He is a fat, snake-headed creature with a corrosive, venomous breath that hoards valuable items. He is destructive, cruel, and murderous.", inventory: 2}
])
Supplier.create!([{name: "Costco", email: "costco@gmail.com", phone_number: "625-231-3454"},{name: "Sams Club", email: "samsclub@gmail.com", phone_number: "555_324-2423"}])