
### Product index
GET http://localhost:3000/products
# Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NDc5OTYxMTV9.anT4MSQM572KNgubq82GzBlC6MqVstfqh8fdpM_77P4
# Content-Type: application/json

### Product show
GET http://localhost:3000/products/10


### Product create

POST http://localhost:3000/products/create
Content-Type: application/json

{
  "name": "Shadrix Silverquill",
  "price": -4.5,
  "image_url": "https://product-images.tcgplayer.com/fit-in/363x363/96467.jpg",
  "description": "test"
}

### product update
Patch http://localhost:3000/products/1
Content-Type: application/json
 
 {
  "name": "Shadrix Silverquill",
  "price": -5,
  "image_url": "https://product-images.tcgplayer.com/fit-in/363x363/235173.jpg",
  "description": "Sha."
}

### product destroy/delete

DELETE http://localhost:3000/products/8


### Users create (signup)
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Average Joe",
  "email": "AJ@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST http://localhost:3000/sessions
Content-Type: application/json

{
  "email": "AJ@test.com",
  "password": "password"
}

### Orders Create

POST http://localhost:3000/orders
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NDgxNDk5MDN9.IEqeMz9ypDbeQ5nWtQin-kox2eCRdxrKjFBoNxano8s
Content-Type: application/json


{
  
  "product_id": 5,
  "quantity": 100
  
}

### Orders show

GET http://localhost:3000/orders/10
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NDgxNDk5MDN9.IEqeMz9ypDbeQ5nWtQin-kox2eCRdxrKjFBoNxano8s
Content-Type: application/json

### Orders index

GET http://localhost:3000/orders
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NDgwODQzMjF9.Gi3hOA42REIqRdjhLqX1YxvhE5ZdNpi5e73DTPSwQ8o
Content-Type: application/json