
### Product index
GET http://localhost:3000/products

### Product show
GET http://localhost:3000/products/10


### Product create

POST http://localhost:3000/products/create
Content-Type: application/json

{
  "name": "Shadrix Silverquill",
  "price": -4.5,
  "image_url": "https://product-images.tcgplayer.com/fit-in/363x363/96467.jpg",
  "description": "test"
}

### product update
Patch http://localhost:3000/products/1
Content-Type: application/json
 
 {
  "name": "Shadrix Silverquill",
  "price": -5,
  "image_url": "https://product-images.tcgplayer.com/fit-in/363x363/235173.jpg",
  "description": "Sha."
}

### product destroy/delete

DELETE http://localhost:3000/products/8